---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: helm

- name: "Download Helm"
  get_url:
    url: "https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz"
    dest: /venky
  tags: download

- name: "Unarchive the package"
  unarchive:
    src: helm-v3.2.1-linux-amd64.tar.gz
    dest: /venky

- name: copy helm binary
  copy:
    src: linux-amd64/helm
    dest: /usr/local/bin
    mode: 0755

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: helm
